### ISSUE TITLE
People Picker retrieving duplicate usernames for same person

### ISSUE THREAD

**Issue by sPoint2013** [purtuga/SPWidgets#25]
SP Widgets People Picker is retrieving duplicate usernames for the same person (#-1;#name) from Unknown List and (#ValidID;#name) from User Information List. It was working fine until Windows Authentication was replaced by Claims Based Authentication. Is there any settings that we need to set in plugin for Claims Based Authentication?
Even tried using the new v2.3 version but still having the issues of getting duplicate values for a person.
Any help/thoughts would be much more appreciated?

Technologies Used

SharePoint 2010
JQuery-1.10.2.min
SPServices-2013.01
JQuery-ui-1.10.3.custom
jquery.SPWidgets.min

**Comment by ymihir** [comment]
Hello Paul,
I am getting duplicate names in the following scenario
1. Search for "x" user.
2. Select that "x" user.
3. Again search for "x" user, you will find "x" username twice.
![image](https://cloud.githubusercontent.com/assets/7568187/7018299/4f55cfc0-dd20-11e4-9099-cc5bd2341c44.png)

**Comment by purtuga** [comment]
Is the ID on any of these -1?
Paul
-- sent from mobile

**Comment by ymihir** [comment]
Yes ID is coming as -1. I tried visioinc fix to filter the IDs which are having -1. But the strange thing is, so many other IDs also coming with -1. So if I apply visioinc logic then I am not able to see all the results. I am using Sharepoint 2010.

**Comment by seanmarthur** [comment]
I have noticed this as well, though I thought it was due to my environment's claims configuration. In my case, watching fiddler, the searchprincipals call is truly returning multiples, but only when the user already exists in the Site Collection User Information List (in other words, they have been previously 'resolved' against the site, or 'ensureuser' called, etc.) So one of results ID will be -1, and the other will be the ID of the SPUser on the site collection.

I resolved this by implementing my own filterSuggestions callback, which checks the display name, email, account ID and account name (loginName) for results which are duplicates. If an account has an ID of -1, and we find a duplicate that doesn't have an ID of -1, we replace that result with the 'local' resolved entity. If an account matches on those fields, but the loginName is different, I append the label with the different loginName in parenthesis. In my case, this occurs when both the windows claims and saml claims accoutns for a user have been added to the site.

**Comment by ymihir** [comment]
So the latest fix was released from your end? I dont know what configuration our sharepoint team is using, whether claims or saml etc.

**Comment by purtuga** [comment]
@ymihir - So that may be what's happening to you as well... for whatever reason, in your SharePoint installation/setup, the API is returning multiple matches for the same user. The widget displays what it gets from the server.

The solution (as @seanmarthur pointed out) is for you to use the `filterSuggestions` input option and implement your own logic for what should be suppressed from the list of suggestion  (or implement what @seanmarthur describes above, if that works for you).

Documentation here: https://github.com/purtuga/SPWidgets/blob/master/documentation/SPWidgets.pickSPUser.md

**Comment by kathleenlgo** [comment]
Hello @purtuga & @seanmarthur  =)  We are facing the same issue and have implemented our own logic for filterSuggestions as suggested.  I followed the guidance from: [this page](https://github.com/purtuga/SPWidgets/blob/master/documentation/SPWidgets.pickSPUser.md).  However, I think something is wrong with how I call the filterSuggestions method or declare it because we are seeing "Function expected" error.  Was just wondering if you can share a sample .js file that makes use of filterSuggestions?  Will try to use it as reference on how it should be done.. Thank you so much!

**Comment by purtuga** [comment]
@kathleenlgo can you post your code for the setup of the picker so that I see how you have the filterSuggestions setup?

**Comment by kathleenlgo** [comment]
Thank you, Paul.  I've spoken to a colleague and updated the js.  Will try it out first.  Thank you! =)
