### ISSUE TITLE
Pieople picker - double result

### ISSUE THREAD

**Issue by spbsmile** [purtuga/SPWidgets#66]
Hello!

I have managed to successfully setup the widget in my SharePoint page, but i have noticed that the people picker give me "double result".

example:
query = Popov
search result: 

- Popov A. B

-  Popov A.B

- Popova B.L

- Popova B.L

expect search result: 
 - Popov A. B

-  Popova B.L

[screenshot](http://i.imgur.com/IzmxQQh.png)

why do I get this "double result"? 
how to get the expected result ?

Thank you,
Andrei.

**Comment by purtuga** [comment]
Hi Andrei. The trouble you are experiencing is caused by how your SharePoint environment is configured.  The API is returning two entries for those users.  The only way around it is for you to filter out the one entry that should not be shown.  The widget has an input parameter that allows you to do that.  Take a look at 'filterSuggestions' input option. 
Paul
-- sent from mobile

**Comment by spbsmile** [comment]
Thx, Paul
