### ISSUE TITLE
SPControlUpload No File message even when a file is selected

### ISSUE THREAD

**Issue by EGLimon** [purtuga/SPWidgets#75]
Hi, I have  a problem with the ControlUpload, that you can see in the image, basically  after initialize without any advance option$("div.file_upload").SPControlUpload({ listName: "Documents" }); I choose a file, click upload but the message "No file selected" appears, any idea why is this happening?

Note:
I’m using O365 with Jquery 1.12.4, jqueryui 1.12.1 and the last version of spservices and spwidgets.

hope you can help me.

![image](https://user-images.githubusercontent.com/23127388/26897850-83548d18-4b8f-11e7-8897-b92b6b4e83af.png)

**Comment by purtuga** [comment]
I'll have to try the demo app on o365 to see if I can recreate.
What browser are using?

Paul

-- sent from mobile

**Comment by EGLimon** [comment]
I’m using IE11, Debugging I find out that in the validation for a No file selected
`7137: if (!page.find('input[type=\'file\']').val())`
page has 2 input file so i just put .last() to find the correct one, with that the plug in can upload to the root only, apparently because the syntax of the upload link is different or something like that, so I changed
From
` 7006: opt._uploadUrlParams = '?List=' + encodeURIComponent(opt.listName) + '&RootFolder=' + encodeURIComponent(opt.folderPath) + '&Source=' + encodeURIComponent(opt.uploadDonePage) + '&' + new Date().getTime() + '=1&' + opt.uploadUrlOpt;
`
To
`7006: opt._uploadUrlParams = '?List=' + encodeURIComponent(opt.listName) + '&RootFolder=' + encodeURIComponent(opt.folderPath) + '&IsDlg=1';`

And with this uploads with folder path, but currently after the upload an error on the page UploadEx.aspx appears and i don't know why this iframe is even loaded. 
If I solve this I’ll let you know but with my knowledge about this is kind a difficult, so if you have an advice would be appreciated.

**Comment by purtuga** [comment]
Thanks for this. 
Its possible that this is currently broken (as you point out) in O365 - they are constantly changing  and due to the approach taken by this widget, its fragile depending on what they change. This is also a pain to debug.  I normally have to take the URL to the upload page and then use it directly in a separate browser to observe its behavior.   Because this is O365, which actually support uploading document to libraries, I would recommend that you find a solution that uses the more recent APIs, rather than this approach. 

Sorry i have not had a chance to test this... I will try this weekend.

**Comment by panchete** [comment]
Hello,
I would like to know if it works with Internet Explorer 8 and SharePoint 10?
Thanks.

**Comment by purtuga** [comment]
Hi... Is you question related this post? or a new question? if a new question, please create a new post.
